ctng_cpu_arch:
  - aarch64         # [not linux32]
ctng_vendor:
  - conda_cos7      # [not linux32]
ctng_target_platform:
  - linux-aarch64   # [not linux32]

zip_keys:
  -
    - ctng_cpu_arch
    - ctng_vendor
    - ctng_target_platform
