travis:
  secure:
    BINSTAR_TOKEN: criH8I9WTv7l6gpHbTdfNDpJpst8clcC4CdqI/N2wP5YYjlKdHB/EhmlrTDQKio96f+7d3z0ud4S7VTJENFXx4yalLabWlYuA4/EtN/fSu2rZvt1Z8R0CxbGVEs8zIaW94FwprfKv2vXF1Sc5+GsLg+Sgy2ar2fou2xbZK7ZAS6s9Cs6l52s9mBzl/UWV/l3ec7VfOoCWyTparJFFBNNtFoRc2aroN5jwjgbMuExP5ytOToQedgairZLXZ6BDa/xccoXOivJ5dkIkiP2bSZhQ6mP72itB5qW1AttTrXU3t5bEwpXPLB2+g0DFFdITmAIVvOn3KYm6INX37as8fI5sUToXjRoPczDj8nMbeOTZ5ENo9a4+tTHiqm49ySlHMFdF9A6Y+/Nb03e6mYk+8tt3FoWs7t8xqnPkW+/9EsJk55nsm25av2ZVkVlLwzRITChFGn6Py07RuafmkQWNIN9wozoNFYiBkhC2sHoIJbpPBIukPw95rDrpQ+joNfIk2sSuSpMqNnWBz4z7MFaxmszKtC9LedLD6b8mM43ZQw5JYrqfZ/Mk4Hy0UfcyEtX6Z/XQUPDT972EKdBzd6CHmN9sYFYdyXnM3kRtm0OenhHvZBk77IJ2seDSk+7asXjLm7CrfqqNvUeEjGGlrHLo3f8wnWPHBOikOJq3rxtgDUKmq4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
