travis:
  secure:
    BINSTAR_TOKEN: h8+BIGuvm70flZH5v9octamOaWqMwwIxNKI+k3ZqX41TWwJWQwxGRI3HY6TYpkP7M78tR/H6hgMyocLfUOFu3UcUBkzmu4btJPFnlheNsrQkuGf00k/0vS7xEYlAFTirwVcl1P9AITg2yiS6UHlfpLNaUXy1EONaYDfrARPZi2BtIwQNFxh2e9Iql6OXAu5tvdef/bzxt1X0nPX19hajp938CDzBpHysX58nDfZf7Pej5WCYhhp/KrB6xF5ADHoOxXqdflLsJZNQfUf1l0qKdl6jHM9hFqpDZqqr8gaKtfBW4htCCJ8mgh0AXA5B0bWCqgYzbWRd0IbQ8DBZRcJLI/iIDwCmQjVbI1kt1/YXNe6z9PR6K+2+EOQLpgKPKQPhFsoEatqC6rZC5FLneSKOfBch3E6jgceFPjSClvPh9G+TyEdUPKZtFxj1qjHKstW4jnsnLKms76xcuuGz4GiJpW/8Arj53yhLY4jkUwXVHT8B148wFVVkGM5bx5Z1OLFvnPnqhiS13kHg0QCGQXoMhzFEiZJwwJDYxQtdJpcexH2uzLMU6acVjGc3/o6cF70F3Tq7sumbfeQ0M2vRNAZ5Q+1GxDvz2AA+N0CVCdRRCMPOklUwmQ0cwpPMgNGbnivJmNrU7ygTc3EvJPweDLc0aKGnd1o6LzEWcojL/5oHLlg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
